[build]

  base = "client/"
  publish = "client/build/"
  command = "yarn build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
    REACT_APP_API_URL= "https://webauth-iii-challenge.herokuapp.com"